### ISSUE TITLE
[BE] QueryDSL을 적용한다

### ISSUE THREAD

**Issue by kth990303** [woowacourse-teams/2022-nae-pyeon#421]
## 기능 상세
- 아래와 같은 어마어마한 JPQL을 리팩터링하는 것이 최우선 목표이다.
```java
 @Query(value = "select distinct new com.woowacourse.naepyeon.service.dto.WrittenMessageResponseDto"
            + "(m.id, r.id, r.title, t.id, t.name, m.content, m.color, "
            + "case when r.recipient = com.woowacourse.naepyeon.domain.rollingpaper.Recipient.MEMBER then p.nickname "
            + "when r.recipient = com.woowacourse.naepyeon.domain.rollingpaper.Recipient.TEAM then t.name "
            + "else '' end) "
            + "from Message m"
            + ", Rollingpaper r"
            + ", Team t"
            + ", TeamParticipation p "
            + "where m.rollingpaper.id = r.id "
            + "and r.team.id = t.id "
            + "and p.team.id = t.id "
            + "and m.author.id = :authorId "
            + "and (p.member.id = r.member.id or r.member.id is null)")
Page<WrittenMessageResponseDto> findAllByAuthorId(@Param("authorId") final Long authorId,
                                                  final Pageable pageRequest);
```
- QueryDSL을 적용함으로써 성능을 향상시키고 복잡한 쿼리의 문법 오류를 컴파일 시점에 확인할 수 있게 하자. 

1. `MessageRepository`를 제외한 레포지토리는 custom repository impl 로 factory를 들고 있도록 
2.  `MessageRepository`는 JPAQueryFactory를 들고 있는 클래스 생성 -> 바로 DTO로 변환해서 특수한 상황에서만 쓰이기 때문에 별도의 custom repository로 사용 (엔티티로 뽑으면 N+1 문제 발생)

**Comment by kth990303** [comment]
## queryDSL 트러블슈팅

- queryDslConfig 클래스를 따로 생성해준 후, 아래 방법대로 하면 No Bean 에러가 뜬다.

### QueryDslConfig.class

```java
@Configuration
public class QueryDslConfig {

    @PersistenceContext
    private EntityManager em;

    @Bean
    public JPAQueryFactory init() {
        return new JPAQueryFactory(em);
    }
}
```

### MemberRepositoryImpl.class

```java
@RequiredArgsConstructor
public class MemberRepositoryImpl implements MemberRepositoryCustom {

private final JPAQueryFactory queryFactory;

@Override
public Optional<Long> findMemberIdByPlatformAndPlatformId(final Platform platform, final String platformId) {
    return Optional.ofNullable(queryFactory
            .select(member.id)
            .from(member)
            .where(member.platform.eq(platform).and(member.platformId.eq(platformId)))
            .fetchOne());
}
}
```

### 결과

```java
Failed to load ApplicationContext
java.lang.IllegalStateException: Failed to load ApplicationContext
  Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'memberRepositoryImpl' defined in file [/Users/kth990303/Desktop/woowacourse/2022-nae-pyeon/backend/build/classes/java/main/com/woowacourse/naepyeon/repository/member/MemberRepositoryImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.querydsl.jpa.impl.JPAQueryFactory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
		at app//org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
		... 86 more
	Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.querydsl.jpa.impl.JPAQueryFactory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
		at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1801)
		... 104 more
```

[[Spring Boot에 QueryDSL을 사용해보자](https://tecoble.techcourse.co.kr/post/2021-08-08-basic-querydsl/)](https://tecoble.techcourse.co.kr/post/2021-08-08-basic-querydsl/)

### 해결 방법

- @DataJpaTest는 스프링 빈을 모두 등록하지 않고, 엔티티와 EntityManager 정도만 등록한다.
    - QueryDslConfig에서 빈으로 등록해준 JPAQueryFactory 역시 등록해주지 않는다.
    - RepositoryTest에 아래와 같이 해주자
    
    ```java
    @Import(QueryDslConfig.class)
    ```

**Comment by kth990303** [comment]
## queryDSL 구조

![image](https://user-images.githubusercontent.com/57135043/190635532-7e28d64a-3345-4baf-916c-52ca847c4c35.png)


출처: 인프런 김영한 - queryDSL 강의자료

**Comment by kth990303** [comment]
## findByXXXId 의 쿼리 성능 개선

연관관계가 있을 경우 특정 엔티티가 아닌 엔티티의 id로 조회하면 join절이 나간다. 따라서 성능 상으로 좋지 않다.

- Spring Data JPA의 경우

```java
List<TeamParticipation> findByTeamId(final Long teamId);
```

![image](https://user-images.githubusercontent.com/57135043/190635629-23e6ba12-d4dc-4629-82ba-d25e468952a5.png)


 → XXX의 식별자로 조회하므로 XXX 테이블을 조인해서 가져온다. Spring Data JPA의 기능으로 JPQL이 의도치 않게 추가적으로 호출해서 사용되는 것. 

- QueryDSL로 변경할 경우

```java
@Override
public List<TeamParticipation> findByTeamId(final Long teamId) {
    return queryFactory
            .selectFrom(teamParticipation)
            .where(isTeamIdEq(teamId))
            .fetch();
}
```

![image](https://user-images.githubusercontent.com/57135043/190635684-80109399-64e7-4caf-b003-efa02ec5285d.png)


 → 정상적으로 `left outer join` 대신 where절로 처리한다. JPQL을 사용하기 때문

### 참고

[[[Spring Data JPA] findByXXXId 는 불필요한 join을 유발한다](https://velog.io/@ohzzi/Data-Jpa-findByXXXId-%EB%8A%94-%EB%B6%88%ED%95%84%EC%9A%94%ED%95%9C-join%EC%9D%84-%EC%9C%A0%EB%B0%9C%ED%95%9C%EB%8B%A4)](https://velog.io/@ohzzi/Data-Jpa-findByXXXId-%EB%8A%94-%EB%B6%88%ED%95%84%EC%9A%94%ED%95%9C-join%EC%9D%84-%EC%9C%A0%EB%B0%9C%ED%95%9C%EB%8B%A4)

**Comment by kth990303** [comment]
## 해당 회원이 작성한 메시지 목록 조회하는 쿼리 개선

- cross join → left outer join -> inner join
- 트러블슈팅
    - DTO를 반환하므로 Projections을 이용해야 하는데, 해당 클래스에는 count()를 지원해주지 않아 Pagination에 애를 먹음
    - 해결 방법
        - 반환 꼴: stream을 이용한 count 사용 `return new PageImpl<>(content, pageRequest, total);`

```java
return queryFactory
            .select(makeProjections()) // DTO 만들기
            .from(message)
            .join(teamParticipation).on(message.rollingpaper.team.id.eq(teamParticipation.team.id))
            .where(isAuthorIdEq(authorId)
                    .and(message.rollingpaper.member.id.isNull()
                            .or(message.rollingpaper.member.id.eq(teamParticipation.member.id))
                    )
            )
            .distinct();
```
![image](https://user-images.githubusercontent.com/57135043/190635906-6b76c6bc-34cf-48ce-8e56-aae1c7186111.png)

- left outer join → inner join
